site_name: Gran Turismo Modding Hub
site_description: The modding hub for all Gran Turismo needs
site_url: https://nenkai.github.io/gt-modding-hub/
repo_url: https://github.com/Nenkai/gt-modding-hub
repo_name: nenkai/gt-modding-hub

copyright: Copyright &copy; 2023 Nenkai - If this website was useful, please make a mention! This page is not affiliated with Polyphony Digital or Sony Interactive Entertainment.

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: deep purple
      accent: blue

nav:
  - Home: index.md

  - PS2 (GT3/GT4/TT):
    - Index: ps2/index.md
    - GT3 / GTC:
        - Getting Started: ps2/getting_started.md
        - Patches / Cheats: ps2/gt3/patches.md

    - GT4 / GT4P / TT:
      - Basics:
        - Getting Started: ps2/gt4/getting_started.md
        - Folder/File Structure: ps2/gt4/file_structure.md

      - SpecDB (Car Specs): ps2/gt4/specdb.md
      - Miscellaneous: 
        - Loading Clock Colors/Errors: ps2/gt4/misc/loading_clock_colors.md
      - Patches / Cheats: ps2/gt4/patches.md

    - Other:
      - Executables (CORE.GT3/CORE.GT4): ps2/executables.md

  - PS3 (GT5/GT6):
    - Getting Started: ps3/getting_started.md
    - Basics: 
      - Volume System: ps3/basics/volume_system.md
      - Folder/File Structure: ps3/basics/file_structure.md
    - Text Editing: ps3/text_editing.md
    - Textures/Image Editing: ps3/textures.md
    - Music Tracks / SFX: ps3/music_tracks.md
    - Car Sound Editing: ps3/car_sound_editing.md
    - SpecDB (Car Specs): ps3/specdb.md
    - Events: ps3/events.md
    - Adhoc: ps3/adhoc.md
    - Movies: ps3/movies.md
    - Fonts: ps3/fonts.md
    - Other:
        - Optimal Modding Setup: ps3/other/optimal_setup.md
        - Command Line Arguments: ps3/other/command_line_args.md
        - FSRoot: ps3/other/fsroot.md

  - General Concepts:
      Volume: concepts/volume.md
      SpecDB: concepts/specdb.md
      Adhoc: 
        - Adhoc Explained: concepts/adhoc/adhoc.md
        - TinyWeb: concepts/adhoc/tinyweb.md

  - Formats:
    - Basic Information: formats/abstract.md
    - Database Formats:
      - .dbt - Database Table: formats/database/dbt_database_table.md
      - .idi - Label Information: formats/database/idi_label_information.md
      - .sdb - String Storage/Database: formats/database/sdb_string_database.md
      
    - Textures:
      - .img - TXS3/TextureSet3: formats/texture/img_txs3_textureset3.md

    - Audio:
      - .lib - BGM Library: formats/audio/bgml_bgm_library.md
      - .esgx - Engine SGX: formats/audio/esgx_engine_sgx.md
      - .sg(d/b/h) - SGX: formats/audio/sgd_sgh_sgx_data.md

    - Adhoc:
      - .adc - Adhoc Script: formats/adhoc/adch_adhoc_compiled.md
      - .gpb - GpbData: formats/adhoc/gpb_gpbdata.md

    - Fonts:
      - .vec - NVEC: formats/fonts/vec_nvec.md

    - Volume: 
      - PS3 Volume/PDIPFS: formats/volume/ps3_volume.md

    - Other Formats:
      - .rt2 - RText (Localization): formats/rt2_localization.md
      - CORE - PS2 Executables: formats/ps2_core.md
      
    - Compression:
      - Headers: formats/compression/compression_formats.md

  - Game Builds:
      - builds/game_builds.md
      - Gran Turismo Concept: builds/gt3concept.md
      - Gran Turismo 4 Prologue: builds/gt4p.md
      - Gran Turismo 4: builds/gt4.md
      - Tourist Trophy: builds/tt.md
      - Gran Turismo 5 Prologue: builds/gt5p.md
      - Gran Turismo 5: builds/gt5.md
      - Gran Turismo 6: builds/gt6.md
      - Gran Turismo SPORT: builds/gt7sp.md
      - Gran Turismo 7: builds/gt7.md
      

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - social:
      cards_color:
        fill: "#2F2F3E"
  - search:
      lang: en
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.io/gtonline

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Nenkaai

    - icon: fontawesome/brands/github 
      link: https://github.com/Nenkai
      
extra_css:
  - stylesheets/extra.css